# Generated by Django 4.1.7 on 2023-03-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_bio',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
