# Generated by Django 4.2 on 2023-04-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='room_url',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_1_in_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_2_in_room',
            field=models.BooleanField(default=False),
        ),
    ]
