# Generated by Django 4.2 on 2023-05-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='preferred_grade',
            field=models.IntegerField(choices=[(9, 9), (10, 10), (11, 11), (12, 12), (0, 'No Preference')], default=0, null=True),
        ),
    ]
