# Generated by Django 4.2 on 2023-04-14 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WebApp", "0002_user_user_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="in_queue",
        ),
    ]
