# Generated by Django 4.2 on 2023-04-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_remove_chatroom_room_url_chatroom_user_1_in_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='user_1_in_room',
            new_name='user1_in_room',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='user_2_in_room',
            new_name='user2_in_room',
        ),
    ]
