# Generated by Django 4.1.4 on 2022-12-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_user_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
    ]
