# Generated by Django 4.1.4 on 2022-12-24 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_chatroom_queueitem_delete_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_calls',
            field=models.ManyToManyField(blank=True, related_name='recent_calls', to=settings.AUTH_USER_MODEL),
        ),
    ]
