# Generated by Django 4.2 on 2023-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_queueitem_preferred_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='call_completed',
            field=models.BooleanField(default=False),
        ),
    ]
